# Generated by Django 3.0.5 on 2020-05-24 10:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post_blog_form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Description', models.TextField()),
                ('Pic', models.FileField(upload_to='images/')),
                ('Author', models.CharField(max_length=50)),
                ('Date_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
